### ISSUE TITLE
Change the getter names to just the field name

### ISSUE THREAD

**Issue by GrayJack** [Robbepop/modular-bitfield#14]
This would make every getter generated by bitfield macro be idiomatic Rust, according to [Rust naming conversions](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter)

**Comment by Robbepop** [comment]
I'd merge a PR that implements this change. ;)

**Comment by nwn** [comment]
I experimented with making this change, and ran into the issue that tuple structs like `#[bitfield] struct Foo(bool, B7);` would try to name its getter methods as `fn 0(&self)`, which is an invalid identifier. This could be left as a special case, still generating `fn get_0()`.

**Comment by Robbepop** [comment]
> I experimented with making this change, and ran into the issue that tuple structs like `#[bitfield] struct Foo(bool, B7);` would try to name its getter methods as `fn 0(&self)`, which is an invalid identifier. This could be left as a special case, still generating `fn get_0()`.

This should be properly documented.
