### ISSUE TITLE
Add documentation to all generated functions and respect visibility

### ISSUE THREAD

**Issue by WorldSEnder** [Robbepop/modular-bitfield#21]
Currently `::new()` comes without documentation. But more importantly, it doesn't respect the annotated visibility of items.

The generated struct is declared public, the getters are public, etc. Instead it should use the visibility declared in on the [fields](https://docs.rs/syn/1.0.42/syn/struct.Field.html) and use that for the declared setters and getters.

As a workaround, I currently wrap all #[bitfield]s in a private module and expose them only through a wrapper.

**Comment by Robbepop** [comment]
That's a really good idea!
