### ISSUE TITLE
Support tuple structs

### ISSUE THREAD

**Issue by dtolnay** [Robbepop/modular-bitfield#4]
For example `struct Example(B1, B7, B8)` might have:

- get_0 and set_0 for B1
- get_1 and set_1 for B7
- get_2 and set_2 for B8

**Comment by Robbepop** [comment]
Implemented by https://github.com/Robbepop/modular-bitfield/commit/af61ac3291c7dc66e36b5c7006b5ea6c0fdfd1b8.
