### ISSUE TITLE
Provide bit layout diagrams

### ISSUE THREAD

**Issue by dtolnay** [Robbepop/modular-bitfield#7]
Details about endianness are not self-explanatory from the readme code sample. The code shows that we can put data in and take the same data out, but not how to think about the data representation in memory which would be important for using modular-bitfield to communicate with other systems.

**Comment by Robbepop** [comment]
Implemented by https://github.com/Robbepop/modular-bitfield/commit/02c88b3bb781bacf18fd0c6914ca28d70403dcc5.
